In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
import os

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

In [7]:
model = Sequential()
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Batc  (None, 16)               64        
 hNormalization)                                                 
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
  os.makedirs(output_path)
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
save_weights_only=True) # otherwise full model is saved
tensorboard = TensorBoard(log_dir='logs/' + run_name)
model.fit(X_train, y_train,
batch_size=8, epochs=32, verbose=1,
validation_data=(X_valid, y_valid),
callbacks=[modelcheckpoint, tensorboard])

Epoch 1/32
51/51 [==============================] - 1s 7ms/step - loss: 576.2867 - val_loss: 589.6393
Epoch 2/32
51/51 [==============================] - 0s 3ms/step - loss: 552.9456 - val_loss: 561.3812
Epoch 3/32
51/51 [==============================] - 0s 3ms/step - loss: 533.0521 - val_loss: 530.6301
Epoch 4/32
51/51 [==============================] - 0s 3ms/step - loss: 508.0359 - val_loss: 536.5437
Epoch 5/32
51/51 [==============================] - 0s 3ms/step - loss: 483.8412 - val_loss: 453.7055
Epoch 6/32
51/51 [==============================] - 0s 3ms/step - loss: 449.3979 - val_loss: 399.8633
Epoch 7/32
51/51 [==============================] - 0s 3ms/step - loss: 419.6029 - val_loss: 310.0923
Epoch 8/32
51/51 [==============================] - 0s 3ms/step - loss: 385.4851 - val_loss: 262.9846
Epoch 9/32
51/51 [==============================] - 0s 3ms/step - loss: 353.2139 - val_loss: 249.2196
Epoch 10/32
51/51 [==============================] - 0s 3ms/step - loss: 302.0009 

In [15]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [16]:
y_valid[42]

14.1

In [17]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 [==============================] - 0s 110ms/step


array([[18.509872]], dtype=float32)